def main():
    print()
    print("|------------------------------------------------|")
    print("|                                                | ") 
    print("|             O que você deseja?                 | ") 
    print("|                                                | ") 
    print("|    1) Criar Processo                           | ")              
    print("|    2) Executar próximo                         |")
    print("|    3) Executar processo específico             |")
    print("|    4) Salvar a fila de processos               |")
    print("|    5) Carregar do arquivo a fila de processos  |")
    print("|                                                |")
    print("|------------------------------------------------|")
    print()
    print()